#!/bin/sh

## The variables are set in the docker-compose file. You can run in as well calling the
## docker run --env-file=FILE ...
# SL_TOKEN=token
# SL_LAB_ID=a
# SL_BRANCH_NAME=c

DEBUG=-Dsl.httpDebugLog=yes
LOGGING=-Dsl.log.toConsole=true
PACKAGES="i0.sealights.demo.calculator*"

SL_TOKEN=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL0RFVi1qYXZhLmF1dGguc2VhbGlnaHRzLmlvLyIsImp3dGlkIjoiREVWLWphdmEsaS0wMDc1MmIxMTk0ZTljZmM2YyxBUElHVy1hOGU1ZDIzNS01NGM3LTQ4ZmQtOWE4OS05MDIyOTdiZjE4MTEsMTY3NjU0NTk5MzU1OCIsInN1YmplY3QiOiJTZWFMaWdodHNAYWdlbnQiLCJhdWRpZW5jZSI6WyJhZ2VudHMiXSwieC1zbC1yb2xlIjoiYWdlbnQiLCJ4LXNsLXNlcnZlciI6Imh0dHBzOi8vZGV2LWphdmEtZ3cuZGV2LnNlYWxpZ2h0cy5jby9hcGkiLCJzbF9pbXBlcl9zdWJqZWN0IjoiIiwiaWF0IjoxNjc2NTQ1OTkzfQ.bAJ7nnczwiX-4OQtWmwgiqZfwHFjWPdUkPHfqoU4ztjDrJibFWnnTGNdCjh7Ia7UYAsOsqHJ4UfE8G6PEwX-Ip-LfYk065oXCPQzvTfOnNBlfWvB1kWdqPcXCey4-VT7gaocKNCXeHjBdAX_UHUJs-ZFwx3bpxoA7MWbJPZnjvCk570Ga8--VSwosgxRmyp_AJzLjsKeJ2yHrtS6R30i1xoDfg6VD3q8PZ6n3p-YN0iXlBDEaQwfm_fb3NivPiRtHFaQ1KBi42o_5cTZ14KjOArn45HFPq_de2EeT59qGi_cFJ5y7Q3MzD-dUiH03EKxss5cIY262uf_O6pKWNiJlLnZ7QWZKgvOq_lh2yMCb3ObIAi_vyNnl_Y4lIL6XHhP69eGLp-k8NVDpqUo7fL_blfU9CdhZedqQjk8ca5ubtGCEE0nRiVyIrLZNd2iiPBSVB9WHCDE3OazJcvNmh4M4lyIP5kAUMGWHbDLArSUsFTSAwz9fLh899hpiiyZiL_mX7hhXfjARNx6HK7doVygCwSp6tJrI5PjBTeMIhgauwvnMdWqXsenZGoaHK2IC2Lxg-_vMi-NAlq0Zn035suRJVS9XoVZ2HC2aONHJuChXJ2J7VL3Z5jLhVndWWPwcH2apqQvhtQkHTZpPyDrEM4wpJx-M5nwWmKn-XDKDN3gF4U
SL_LAB_ID=integ_testing_otel_instr
SL_BRANCH_NAME=testing
CALC_APPNAME=demoCalculator
CALC_BUILD_NAME=build_001


java -Dsl.log.level=DEBUG "$DEBUG $LOGGING" \
  -agentlib:jdwp=transport=dt_socket,server=n,address=host.docker.internal:5005,suspend=y \
  -Dsl.workspace=. \
  -Dsl.featuresData.codeCoverageManagerVersion=v2 \
  -Dsl.otel.enabled=true -Dsl.otel.loadEmbeddedAgent=true \
  -Dio.opentelemetry.level=DEBUG \
  -Dsl.sendInitFootprints=true \
  -Dsl.tags=otelcfg \
  -Dsl.featuresData.enableLineCoverage=false \
  -Dsl.ignoreAutoGeneratedMethods=false \
  -Dsl.ignoreMethodsWithoutLineNumbers=false \
  -Dsl.featuresData.ignoreMethodsWithoutLineNumbers=false \
  -Dsl.featuresData.ignoreAutoGeneratedMethods=false \
  -Dsl.buildMapBatchSize=500 \
  -Dsl.includes="$PACKAGES" \
  -Dsl.token="$SL_TOKEN" \
  -Dsl.labId="$SL_LAB_ID" \
  -Dsl.buildName="$CALC_BUILD_NAME" \
  -Dsl.branchName="$SL_BRANCH_NAME" \
  -Dsl.appName="$CALC_APPNAME" \
  -javaagent:../java-agent-bootstrapper-ftv-4.0.0-SNAPSHOT.jar \
  -jar ../build/libs/calculator-0.0.1-SNAPSHOT.jar