GET http://localhost:9080/api/sum/geometric?first=1&ratio=0.6&count=5
Accept: application/json

###
GET http://localhost:9080/api/evaluate/3*91
Accept: application/json
baggage: x-sl-execution-id=b5d1109f-838d-4011-ae30-33912462fdbf,x-sl-test-name=i0.sealights.ftv.runner.RunnerServiceTestA.shouldReturnHelloDateCCC

###

GET http://localhost:9080/api/evaluate/(3*7+4)*0.2
Accept: application/json

###

GET http://localhost:9080/api/evaluate/2*cos(2*3.141592653589793238)
Accept: application/json

###
